module.exports = {
  USER: "USER",
  ROLE: "ROLE",
  SUBJECT: "SUBJECT",
  COURSE: "COURSE",
  PAYMENT: "PAYMENT",
  PAYMENT_METHOD: "PAYMENT_METHOD",
  DOCUMENT: "DOCUMENT",
  DOCUMENT_TYPE: "DOCUMENT_TYPE",
  QUESTION: "QUESTION",
  ANSWER: "ANSWER",
};
